language: python
env: DATA_NAMESPACE="http://vivo.school.edu/individual/"
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:
  - py.test
  - coverage run --source vdm -m py.test
notifications:
  email:
    recipients:
      - lawlesst@brown.edu
      - steven_mccauley@brown.edu
after_success: coveralls
